In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/Users/swayamware/Documents/user_conversion_funnel/Dataset/events.csv")

In [3]:
data.head(5)

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
2  1433221999827     111016  view  318965            NaN
3  1433221955914     483717  view  253185            NaN
4  1433221337106     951259  view  367447            NaN

In [5]:
data.event.unique()

array(['view', 'addtocart', 'transaction'], dtype=object)

In [7]:
data.shape

(2756101, 5)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2756101 entries, 0 to 2756100
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      int64
 1   visitorid      int64
 2   event          object
 3   itemid         int64
 4   transactionid  float64
dtypes: float64(1), int64(3), object(1)
memory usage: 105.1+ MB

In [9]:
data.describe()

          timestamp     visitorid        itemid  transactionid
count  2.756101e+06  2.756101e+06  2.756101e+06   22457.000000
mean   1.436424e+12  7.019229e+05  2.349225e+05    8826.497796
std    3.366312e+09  4.056875e+05  1.341954e+05    5098.996290
min    1.430622e+12  0.000000e+00  3.000000e+00       0.000000
25%    1.433478e+12  3.505660e+05  1.181200e+05    4411.000000
50%    1.436453e+12  7.020600e+05  2.360670e+05    8813.000000
75%    1.439225e+12  1.053437e+06  3.507150e+05   13224.000000
max    1.442545e+12  1.407579e+06  4.668670e+05   17671.000000

In [10]:
data['visitorid'].nunique()

1407580

Funnel stages are derived from available event types in the dataset.

In [12]:
data['event'].value_counts()

event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64

In [13]:
data['timestamp'].head(5)

0    1433221332117
1    1433224214164
2    1433221999827
3    1433221955914
4    1433221337106
Name: timestamp, dtype: int64

Converting Time

In [19]:
data['event_time'] = pd.to_datetime(data['timestamp'], unit='ms')

In [21]:
data['event_time'].min()

Timestamp('2015-05-03 03:00:04.384000')

In [22]:
data['event_time'].max()

Timestamp('2015-09-18 02:59:47.788000')

## Do most users only view or do they progress?

In [23]:
data.groupby('visitorid')['event'].nunique().value_counts()

event
1    1371768
2      25584
3      10228
Name: count, dtype: int64

In [24]:
data.isnull().value_counts()

timestamp  visitorid  event  itemid  transactionid  event_time
False      False      False  False   True           False         2733644
                                     False          False           22457
Name: count, dtype: int64